apiVersion: v1
kind: Pod
metadata:
  labels:
    app: iperf-server
  name: iperf-server
spec:
  containers:
  - name: server
    image: ghcr.io/packetdrop/ndb:latest
    args:
    - iperf3
    - -s
  nodeName: ""
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: iperf-service
spec:
  selector:
    app: iperf-server
  ports:
    - protocol: TCP
      port: 5201
      targetPort: 5201
      name: tcp
    - protocol: UDP
      port: 5201
      targetPort: 5201
      name: udp
---
apiVersion: v1
kind: Pod
metadata:
    labels:
      app: iperf-client
    name: iperf-client
spec:
    containers:
    - name: client
      image: ghcr.io/packetdrop/ndb:latest
      args:
      - /bin/sh
      - -c
      - sleep 1000
    nodeName: ""
    restartPolicy: Never
