apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndb
  labels:
    app: ndb

  replicas: 1

  selector:
    matchLabels:
      app: ndb

  template:
    metadata:
      labels:
        app: ndb
    spec:
      containers:
      - name: ndb
        image: avishnoi/ndb:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
