apiVersion: v1
kind: Pod
metadata:
  labels:
    app: netperf-server
  name: netperf-server
spec:
  containers:
  - name: server
    image: ghcr.io/packetdrop/ndb:latest
    args:
    - netserver
    - -D
    - -d
    - "-4"
  nodeName: ""
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
    labels:
      app: netperf-client
    name: netperf-client
spec:
    containers:
    - name: client
      image: ghcr.io/packetdrop/ndb:latest
      args:
      - /bin/sh
      - -c
      - sleep 1000
    nodeName: ""
    restartPolicy: Never
