apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx
spec:
 replicas: 2
 strategy:
  type: Recreate
 selector:
  matchLabels:
   app: nginx-app
 template:
   metadata:
    labels:
     app: nginx-app
     env: prod
   spec:
    containers:
    - name: nginx-container
      image: nginxdemos/hello:plain-text
---
apiVersion: v1
kind: Service
metadata:
 name: nginx
spec:
 type: NodePort
 selector:
   app: nginx-app
   env: prod
 ports:
 - nodePort: 32410
   protocol: TCP
   port: 80
   targetPort: 80