apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-server
  name: nginx-server
spec:
  containers:
  - name: server
    image: nginxdemos/hello:plain-text
  nodeName: ""
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
    labels:
      app: curl-client
    name: curl-client
spec:
    containers:
    - name: curl
      image: ghcr.io/packetdrop/ndb:latest
      args:
      - /bin/sh
      - -c
      - sleep 10000
  nodeName: ""
  restartPolicy: Never
